[package]
name = "drop_arena"
version = "0.1.0"
edition = "2021"
authors = ["Mark Saving"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-arena = "2.0.2"
